
# La Gobernanza de Datos en PYMEs Emprendedoras

Autora: Bielka Yuvenny Ulloa Reynoso

# Introducción
La gobernanza para datos es una actividad crucial a la hora de manejar datos y todos los procesos y actores que a ello conlleva, para las pequeñas y medianas empresas o PYMES es una herramienta crucial ya 
Que puede ofrecer una visión del mercado más amplia en base al análisis de datos, sin obviar que para las PYMES emprendedoras implementar un sistema puede representar un desafío, ya que estos mayormente son nuevos en el sector o tienen un presupuesto limitado.

En esta era digital la protección de datos es primordial para las organizaciones y es aquí donde entra la gobernanza de datos con sus normas y procedimientos que ayudan a reducir los riesgos de filtración de datos o mal manejo, además de, con la tecnología ayudar en la toma de decisiones a los directivos.

En este capítulo se hará hincapié en este elemento clave que brinda una base de crecimiento a la PYMES, se iniciará con el concepto de gobernanza de datos, la gobernanza de datos para PYMES, además de, sus componentes principales y objetivos de esta manera, se le abre paso a los siguientes temas que lo componen como política y procedimiento de gestión de datos, identificación y clasificación de datos críticos, roles y responsabilidades, medidas de seguridad

# Gobernanza de datos

## Concepto de gobernanza 
La gobernanza como termino general se refiere al manejo, creación e integración de las normativas en una sociedad, en este proceso respecto a las normativas también es integrada la opinión de los actores involucrados.

Este es un término que puede ocasionar confusión puesto que puede ser aplicado en diferentes contextos o áreas y que involucra diferentes actores. Es importante destacar que, los actores son personas físicas o jurídicas que intervienen o influyen en la toma de decisión de la organización.

El concepto de gobernanza a menudo es confundido con gobernabilidad, gobernanza como ya vimos es la conformación de normativas y la aplicación de las mismas con la colaboración de todos los actores involucrados, mientras que, la gobernabilidad es la capacidad que tiene una sociedad de mantener la estabilidad.

El concepto de gobernanza fue utilizado por el filósofo ateniense Platón en la edad media, luego paso a ser utilizado o mencionado en el idioma francés con el concepto gouvernance, más tarde paso al idioma ingles en el 1380 con el termino governance, en los tiempos modernos se fue popularizando para los años de 1990 utilizado en artículos académicos y revistas políticas haciendo énfasis en un nuevo termino que engloba nuevas técnicas que incorporan la opinión de las partes afectadas así como las buenas prácticas en las mismas.

##	Gobernanza de datos en Pymes 

La gobernanza de datos es un sistema de derechos de decisión y responsabilidades por los procesos relacionados con la información, ejecutado de acuerdo con los modelos acordados que describen quién puede tomar qué acciones con qué información, y cuándo, bajo qué circunstancias, utilizando qué métodos. Tomas (2010)

En pymes es de vital importancia el manejo de los datos ya que es una empresa en etapa de crecimiento en un entorno cambiante, la gobernanza en los datos ayudara a modificar el modelo de negocios mediante vayan surgiendo cambios significativos en el mercado y los consumidores, estas aportan ventajas competitivas que pueden ser implementadas.

Una gobernanza de datos tiene tres componentes principales que son:

1.	Tecnología:
Es el componente más importante ya que en él se hace el cerebro de la interacción entre el personal de todos los departamentos.

La entrada, proceso de los datos permite que el sistema lea y organice los datos mediante herramientas tecnológicas que al final arroje datos para ser utilizados en la toma de decisiones.

2.	Profesionales:
Estos son los encargados de la gestión de la tecnología como tal, son quienes analizan y monitorean que las normas sean cumplidas, además, de ayudar al sistema a procesar los datos y convertirlos en datos los cuales puedan ser almacenados.

3.	Procesos:
Es todo el proceso desde la entrada del dato hasta la llegada del dato (datos ya procesados) al data warehouse, entiendo que no solo son estos dos procesos, sino que, el objetivo de este punto es verificar la precisión del proceso y que se modifique el sistema interno si es necesario para que le dato pueda manejar se manera segura.

 En este punto se puede hacer la referencia al control porque aquí se documenta todo el proceso del manejo de dato.


##	Objetivos de la gobernanza de datos en PYMES

1.	Garantizar el correcto manejo de los datos: esto hace referencia a la parte del manejo de datos tanto en la introducción de los datos como la confidencialidad de los mismos.
2.	Mejorar la calidad de los datos: esto se hace con una metodología de buena calidad de datos suministrados, seguridad de los mismos, que permita una recolección de datos más precisa para luego ser utilizada de manera eficiente en el análisis.
3.	Mejorar la toma de decisiones: a través de un análisis más preciso de los datos que proporcionen un apoyo en la toma de decisión a los ejecutivos.
4.	Cumplimiento normativo solido: con la respectiva creación de normativas referentes a los datos se crea la práctica del seguimiento del mismo, para ser más explícitos, la normativa crea una serie de caminos a seguir, cada uno dando respuesta a una situación y cada camino contiene una serie de pautas que los diferentes intermediarios deben cumplir. 
5.	Proporciona una visión más amplia y precisa del mercado.


2.4 . Beneficios de la gobernanza de datos para las pymes emprendedoras
•	Mejorar la calidad de los datos
•	Decisiones más inteligentes
•	Reducir los riesgos de seguridad y privacidad
•	Cumplimiento de la normativa de protección de datos
•	Mejorar la eficiencia y eficacia de los procesos de negocio

# Componentes de la gobernanza de datos

##	  Políticas y procedimientos de gestión de datos
La gestión de datos hace referencia a los procedimientos agotados por la entidad en el manejo del mismo, por lo tanto, cuando hablamos de política de gestión de gastos nos referimos a un documento normativo creado por el órgano encargado que contiene las normativas para la gestión de los datos.

Los objetivos de la política de gestión de datos son:
-	Asegurar un adecuado mecanismo de control, siempre proporcionando la información correcta al actor adecuado.
-	Crear, aplicar, controlar las políticas y los procedimientos y que las mismas sean precisas y eficientes.
-	Introducir adecuadas medidas de seguridad.

El adecuado manejo de datos puede brindarle al emprendedor de pequeñas y medianas empresas una visión estable del mercado, además de, que los consumidores depositen un nivel de confianza adicional por la eficiencia del personal en la ejecución de procesos.

La política de datos se centra en cuatro ejes principales

-	Protección de datos.
-	Mantenimiento y depuración de datos.
-	 Información de calidad.
-	Clasificación de los datos.

Las políticas sobre la gestión de los datos deben ser flexibles como lo es el mundo de la tecnología para que estas sean actualizadas periódicamente y que se vaya adaptando a las nuevas situaciones y tecnologías que se vayan presentando, importante destacar que todo el personal de la organización debe tener acceso a esta información.

Para un PYME estas políticas no solo brindaran protección y buen manejo con los datos, sino que también ayudaran en el proceso de introducción al mercado y en el comprometimiento del personal para desarrollar sus funciones de la manera adecuada.

##	  Identificación y clasificación de datos críticos

Es bien saber que en el mundo de la tecnología y la información contamos con una cantidad de datos ilimitados que cada día crece más, como ya hemos visto antes el manejo y la clasificación de los datos tiene una importancia esencial para la gestión, ya que, datos irrelevantes a nuestras prácticas provocarían confusión a la hora del sistema presentar el informe de los mismos.

Cada dato que es ingresado, procesado y almacenado tiene un grado de importancia que es colocado por la empresa en cuestión y estos son protegidos dependiendo de su grado de confidencialidad, sin hacer referencia a que los datos menos confidenciales tienen menos protección, es importante destacar que todos los datos tienen el mismo nivel de seguridad, lo que varía en ellos es el nivel de accesibilidad que tienen.

Estos datos se clasifican según los criterios de la organización, normalmente de la siguiente manera:

-	Confidencial: los datos confidenciales tienen un grado moderado-alto estos son utilizados con el personal de la organización y con las personas que lo proporcionan, o sea, los consumidores.
-	Secreto: al igual que el confidencial tiene un rango moderado-alto, la diferencia radica en que estos datos son manejados por el personal de áreas de la organización, ejemplo: los datos que se manejan en el departamento de contabilidad no puede ser visto por el personal de marketing.
-	Alto secreto: el rango de este es alto, solo personal de alto rango puede manejar esta información y debe ser manejada con extremo cuidado y seguridad.

Como ya se mencionó los datos son clasificados según su tipo, por lo tanto, estos tienen principios de clasificación y estos son:

1.	Gestión de riesgos: esta es la protección y manejo por el nivel de sensibilidad en los datos y una proyección de riesgos, básicamente, es analizar posibles fugas, modificaciones o perdidas de información según el nivel de accesibilidad a la misma.
2.	Basado en el contenido: en este principio no se toma tan en cuenta la procedencia del dato, sino, el valor que puede aportar al banco de datos, que ya luego de ingresar al sistema será posteriormente procesado, clasificado y almacenado para ser utilizado en datos que aporten valor a la toma de decisiones.
3.	Ciclo de vida: este principio hace referencia a que la información que está en el data warehouse debe ser tomada en cuenta y siempre estar disponible, durante el ciclo de vida del sistema de información hasta que sea destruida

##	 Roles y responsabilidades en la gestión de datos

Un rol son las funciones o comportamientos que una persona o grupo de personas tienen en una organización. “Para el contexto organizacional podemos relacionar el concepto con las tareas asignadas a cada colaborador y así mismo todas las responsabilidades que acarrea a nivel de seguridad, calidad y disponibilidad de por ejemplo los activos información, así pues, dependiendo el marco de referencia y el contexto se oficializan cargos y roles dependiendo de la manera en que la organización se reconoce”. Acero, Santamaria (2022)

Para IBM (2014) estos roles son 6:
1)	Patrocinador ejecutivo.
2)	Consejo de gobierno de datos.
3)	Oficina de gobierno de datos.
4)	Propietario del proceso del negocio.
5)	Administrador de datos.
6)	Guardián de datos.

Si nos centramos en la PYMES que son pequeñas y medianas empresas quizás estos roles puedan variar un poco debido a que en la mayoría de los casos siempre las pequeñas y medianas empresas, más si es un prendimiento suelen cortar presupuesto.

Con la identificación de roles se pueden evitar posible filtración de información, además, de un mal manejo de la misma ya que cada rol representa una responsabilidad directa en la gestión del dato en toda su etapa.

##	 Medidas de seguridad para proteger los datos
La seguridad de los datos con el avance del tiempo se ve más amenazada mediante se van generando nuevas opciones de ciber-ataque, pero, los desarrolladores han ido dando respuestas mediante tecnología de protección de datos y políticas generadas por la empresa para la regulación de la información.

Las medidas de seguridad utilizadas son las siguientes:

1.	Cada persona que interactúe con el sistema deberá poseer un usuario y contraseña y el modulo estará adaptado a sus funciones corporativas, con esto logramos una delimitación de la información y colocamos autor a cada transacción.
2.	Diferentes fuentes de almacenamiento, ya que se debe tener en cuenta una pérdida de información por parte del sistema, estos deben tener varias opciones de almacenamiento que le brinden opciones de recuperación a la organización en caso de que ocurra un incidente.
3.	Realizar Backups periódicamente y realizar borrados seguros que eviten filtración de la información. 
4.	Realizar actualizaciones periódicas del software a utilizar, ya que en el ciber-espacio se crean nuevas formas de estafa a cada minuto.
5.	Introducir softwares de protección de datos en los diferentes dispositivos donde se maneje la información. 

Es importante destacar que los ataques no solo pueden venir del mundo cibernético sino puede venir también de un mal manejo por parte del personal que interactúa con él, es por esto que el personal debe seguir los procedimientos como dicen las políticas.


##	 Medición del desempeño en la gestión de datos

En esta parte se destaca la medición para evaluar el sistema implementado con sus políticas, esta medición lo que se centra es en evaluar las áreas que hayan cumplido con los objetivos, estos tienen una medición estándar por calidad de datos, la seguridad y el cumplimiento de las políticas.

# Implementación de la gobernanza de datos en pymes emprendedoras
Pasos para implementar la gobernanza de datos en la empresa

Consideraciones para la implementación en una pyme emprendedora
Herramientas y recursos disponibles para la implementación


# Conclusiones

Las PYMES emprendedoras presentan un grado adicional de dificultad al implementar una gobernanza de datos por su falta de conocimiento en el manejo del sistema, por otro lado, su implementación puede ser difícil debido a los recursos que esta pueda tener disponible.
La gobernanza puede ayudar a las PYMES emprendedoras a reducir los errores humanos que se pueden producir por el desconocimiento es por esto que la gobernanza se espera que sea cada vez más utilizada en el futuro y la ventaja competitiva crezca en cuanto a este aspecto. 
Finalmente, la adopción de una cultura de datos sólida propiciará la innovación y la competitividad a largo plazo, permitiendo a las PYMES emprendedoras crecer y prosperar en un entorno empresarial cada vez más interconectado y dependiente de la información. Por lo tanto, es fundamental que las pequeñas y medianas empresas inviertan en la gobernanza de datos y desarrollen estrategias adecuadas para maximizar el valor de sus activos de información y mitigar los riesgos asociados.


#References
Ballard, C., Baldwin, J., Baryudin, A., Brunell, G., Giardina, C., Haber, M., O’neill, E. A., & Shah, S. (n.d.). Ibm.com. Retrieved June 22, 2023, from https://www.redbooks.ibm.com/redbooks/pdfs/sg248164.pdf 
de Roles, M., La Integridad, R. Y. M. R. A., & de La Uae Dian, S. Y. D. D. E. I. P. E. L. G. D. E. D. D. E. L. S. D. E. G. D. E. L. R. Y. P. (n.d.). EDISSON STICK ACERO ACEVEDO DIANA MARCELA SANTAMARIA RIOS. Edu.Co. Retrieved June 22, 2023, from https://bdigital.uexternado.edu.co/server/api/core/bitstreams/ce7e2689-5c09-474b-9b7f-c1136f78960d/content 
De, S., & Integrado, G. (n.d.). POLITICAS Y PROCEDIMIENTOS TRATAMIENTO DE DATOS PERSONALES. Visionamos.com. Retrieved June 22, 2023, from https://www.visionamos.com/wp-content/uploads/2021/10/DSGSI-03-Politicas-Procedim-Tratamiento-Datos-V-1-copia.pdf 
The the DGI data governance DGI Data Governance Framework framework. (n.d.). Datagovernance.com. Retrieved June 22, 2023, from https://datagovernance.com/wp-content/uploads/2020/07/dgi_data_governance_framework.pdf 
(N.d.). Cloudfront.net. Retrieved June 22, 2023, from https://d1wqtxts1xzle7.cloudfront.net/54901867/La_Gobernanza_hoy-libre.pdf?1509743536=&response-content-disposition=inline%3B+filename%3DLA_GOBERNANZA_HOY_INTRODUCCIONl.pdf&Expires=1687378534&Signature=P4TkHHNBtKxFZ6KwBNmr6guQCflzUP9N1rYEqhJc4ahKMuDXHlrfDRUngVHBl~XnhDVEKbaivZnR8GNfRIo-U~o78OqMKxe9wupoq7-SpfqasYpvB9LiCcNmA~wsqoQLA08NhgxEdiS0hFnPgZAJE7GQ5hjm3-j3wZHL59Tpqwucr8VyNKzpCOQZQ1RAL010mBMEosSTX5iMUiuvOxDW9MAoBW9kPSXGOxe3qD5A0na2PaX~byQFLAVC7TjAhs~wzBueM9SprGeE0t4jypIwHgJFvAEJgVjgwtlMlktr~MW9MxoJph3pmsNNYFb5MgY7Bl~5nOCyEyPOcnH~9fteDw__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA 







