# Introducción {.unnumbered}

- The  development  of technology and the mounting use of information communication technology (ICT) have an important role for the business organisations and operations
- Although the need of having a reliable ICT is apparent, there are many business organisations that do not adopt this technology. For a large business organisation with ample human and financial resources, the adoption of ICT  may not be a significant problem.  However,  for  small-sized  business  organisations  which face  resources limitations, the ICT adoption becomes a problem. 
- This issue turns out to be more severe for small businesses in developing countries such as Indonesia, in which its entrepreneurs face education and cultural constraints (Anggadwita et al., 2015; Tambunan, 2011)
- This is not a book about studying the adoption of ICT and data by entrepreneurs, but about how to help them 

## Benefits and Types of Data

- ICT could help the business organisation to achieve a greater efficiency and lower cost in their operation. 
- Impact of data on business productivity, cost, revenue, and profitability (Gërguri-Rashiti et al., 2017). 
- Data and ICT to push innovation and business performance (Ramadani et al., 2016). 
- From a consumer perspective, ICT, especially the internet, has an impact on the way consumers purchase products and services. 
- The Internet more reliable and affordable for many customers. It is now easier for the consumer to find information and vendors of a product or service, not only from the local market, but also from the global market. 
- Having well developed and operationalised ICT is an important  factor  to  build  the  competitive  business  advantage  (Gërguri-Rashiti  et  al., 2017).

### Index

1. Context and Background
  - Entrepreneurship and tourism
  - Entrepreneurs, data and ICT
  - Characteristics of the entrepreneurial firm
2. Understanding data
  - What is data?
  - Benefits of data
  - Types of Data
  - The Data life-cycle
  - Management of data in small enterprises
3. The Entrepreneurial data-driven process
  - The classic vs data-driven entrepreneurial process
4. Methods and Technologies
  - Deployment methods
  - Cloud and entrepreneurs
  - Low code
  - Big data for entrepreneurs
5. Data considerations for Tourism Entrepreneurs
  - Ética de Datos y Emprendimiento
  - Finanzas de Datos para Emprendedores
  - Conocimiento del Cliente a través de los Datos
  - La Gobernanza de Datos en PYMEs Emprendedoras
6. Starting-up a data-driven entrepreneur (Wrapping all up)
  - Stages
  - Leadership styles
7. What's next
  - Role of AI
  - IoT
  - Big Data and analytics

